### ISSUE TITLE
Status: Not Charging

### ISSUE THREAD

**Issue by gdlin** [vsimkus/gnome-shell-extension-dell-command-configure-menu#1]
Hello, 

Thanks for this plugin! I actually had something really similar in mind but never took the time to actually do it!. I work with a mac as well as my Fedora (Gnome) main PC. The thing is that the mac is almost always plugged in, and now it shows something like "Battery not charging, rarely used on battery" which informs you **why** it's not charging.

However, when I set the charging configuration through cctk, my battery status stays in "Estimating". What I was thinking was to show something similar as I've described above, like "not charging", since we actually know that it won't be charging unless the setting is changed.

[This extension](https://bitbucket.org/pvpublic/mbpbat/src/master/extension.js) manipulates the battery percentage, so maybe we can reuse parts of that code here? What do you think?

**Comment by vsimkus** [comment]
Thanks for the suggestion. 

Changing the battery status would not be difficult to implement, however this may easily break other extensions or the power-menu UI in the gnome shell. Personally, I don't find the text "Estimating..." very irritating and don't feel that the risk of breaking the gnome-shell UI elements or other extensions is worth the change.

The source of the issue is the following code in the gnome-shell https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/js/ui/status/power.js#L64-101. You can run `upower -i /org/freedesktop/UPower/devices/battery_BAT0` and you'll see that the battery state is `charging` when the power is actually bypassing the battery (due to the setting in CCTK). Then, I think the `seconds = this._proxy.TimeToFull;` returns 0, which in turn returns "Estimating...".

I suppose the most proper way to fix it would be to introduce a new state in UPower for when the power is plugged in but the battery is bypassed (might not be easy to detect this state), and then introduce the necessary change in gnome-shell to handle it.

If it really bothers you, you could create a separate extension that does just that, or just fork this one and make the change, just beware that it may break other things in the future.

**Comment by vsimkus** [comment]
Just an update. It seems that with my current version of UPower (v0.99.17-1) the state returned by `upower -i /org/freedesktop/UPower/devices/battery_BAT0` is now `pending-charge` when the battery is not charging but the cable is plugged in. And so it properly shows "Not Charging" instead of "Estimating..." in the gnome-shell. So the issue got fixed at the source as I suggested before.

**Comment by gdlin** [comment]
@vsimkus I've just updated my computer and I can confirm that this is working perfectly
![image](https://user-images.githubusercontent.com/1306672/192291167-d2fd526c-ddb7-420c-bffb-f20ee7f0df61.png)

Thanks for the update!
